title: R.A.N.D. Distribution
description: "Black Wax Distribution"
baseurl: ""
url: "https://reecebwalker.github.io/randdistro"

# Build settings
markdown: kramdown

permalink: pretty

navigation:
  - path: "/labels"
    id: labels
    name: Labels
  - path: "/releases"
    id: releases
    name: Releases
  - path: "/ordering"
    id: ordering
    name: Ordering

collections:
  labels:
    output: true
  releases:
    output: true

defaults:
  - scope:
      path: ""
      type: labels
    values:
      layout: label
      class: label
  - scope:
      path: ""
      type: releases
    values:
      layout: release
      class: release-detail

exclude:
  - "*README.md"
  - "*.sh"
  - "package.json"
  - "node_modules/"
  - "gulpfile.js"
